### ISSUE TITLE
User-generated panoramas don't load

### ISSUE THREAD

**Issue by louisroy** [heganoo/GSVPano#1]
It looks like "unofficial" panoramas can't be loaded through GSVPano. They all return a 400 (Bad Request) status code along with a completely black image. Changing the zoom has no effect whatsoever.

Couple of problematic IDs :
- [_ePRW_juj-gAAAAGOqmIVA](http://maps.google.com/cbk?output=tile&panoid=_ePRW_juj-gAAAAGOqmIVA&zoom=1&x=0&y=0&1431003867121)
- [_6sKLliDFZIAAAAGOsU39Q](http://maps.google.com/cbk?output=tile&panoid=_6sKLliDFZIAAAAGOsU39Q&zoom=1&x=0&y=0&1431004052504)
- [PzmTwr3ES8QAAAQZK7DN4g](http://maps.google.com/cbk?output=tile&panoid=PzmTwr3ES8QAAAQZK7DN4g&zoom=1&x=0&y=0&1431004129979)

The onError and onNoPanoramaData events are not fired either when this happens.

If you have any pointers, I'd be happy to help and prepare a pull request.

**Comment by ghost** [comment]
Just ran into the same issue, no errors thrown.
